FROM node:alpine as myApp
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM nginx
EXPOSE $CLIENT_PORT
ADD ./nginx/default.conf /etc/nginx/conf.d/default.template
# Necessary command to replace environment variables in default.conf
CMD sh -c "envsubst '\$CLIENT_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
COPY --from=myApp /app/build /usr/share/nginx/html