language: generic 
sudo: required
sevices:
    - docker

before_install:
    - docker build -t dariodemix/multicontainerapp-test -f ./client/Dockerfile.dev ./client

script:
    - echo "testtttt"

after_success:
    - docker build -t dariodemix/multi-client -f ./client/Dockerfile.prod ./client
    - docker build -t dariodemix/multi-nginx -f ./nginx/Dockerfile.prod ./nginx
    - docker build -t dariodemix/multi-server -f ./server/Dockerfile.prod ./server
    - docker build -t dariodemix/multi-worker -f ./worker/Dockerfile.prod ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push dariodemix/multi-client
    - docker push dariodemix/multi-nginx
    - docker push dariodemix/multi-server
    - docker push dariodemix/multi-worker
    