version: '3'
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        depends_on: 
            - api
            - client
        environment: 
            - CLIENT_PORT=${CLIENT_PORT}
            - API_PORT=${API_PORT}
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    redis:
        image: 'redis:latest'
    api:
        build:
          dockerfile: Dockerfile.dev
          context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        depends_on:
            - postgres
        environment: 
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - PGUSER=${PGUSER}
            - PGHOST=${PGHOST}
            - PGDATABASE=${PGDATABASE}
            - PGPASSWORD=${PGPASSWORD}
            - PGPORT=${PGPORT}
            - API_PORT=${API_PORT}
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.prod
            context: ./client
        environment: 
            - CLIENT_PORT=${CLIENT_PORT}
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
          dockerfile: Dockerfile.dev
          context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT={REDIS_PORT}

