FROM nginx
ADD ./default.conf /etc/nginx/conf.d/default.template
# Necessary command to replace environment variables in default.conf
CMD sh -c "envsubst '\$CLIENT_PORT \$API_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"